# Generated by Django 4.1.6 on 2023-02-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('site_url', models.TextField()),
                ('twitter_url', models.TextField(verbose_name='Twitter')),
                ('facebook_url', models.TextField(verbose_name='Facebook')),
                ('linkedin_url', models.TextField()),
                ('youtube_url', models.TextField(verbose_name='Youtube')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_hidden_course', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=False)),
                ('mentor_ads', models.BooleanField(default=False)),
                ('email_ads', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
