# Generated by Django 4.1.6 on 2023-02-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_course_order_courseitemfile_courseitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='image_show',
        ),
    ]
